### ISSUE TITLE
"Can not fetch status from the relayer" despite everything else working.

### ISSUE THREAD

**Issue by MasterGuardian** [tornadocash/relayer#7]
Hey, I hope you can help me understand what I am doing wrong.

I set up a relayer (deployed with docker-compose) and everything is running and working (./status etc. all 'normal').

My ENS Domain mainnet.\*.eth is pointing to my address mainnet.*.com
and kovan.*.eth to kovan.\*.com and both to the ip of the server the relayer is running on.

Using my "kovan.\*.eth" domain as custom relayer for the kovan version of tornado.cash works just fine, but if I want to test the "mainnet.\*.eth" domain for the mainnet version I always get the "Can not fetch status from the relayer" message.

They are all setup the same way, so why is the kovan relayer working, but the mainnet one not?

Thanks in advance! :)

EDIT Solution was:
Have at least 0.15 ETH in your relayer address.

**Comment by rstormsf** [comment]
@MasterGuardian interesting... is this still an issue? 
Make sure you are on the latest commit version. 
FYI - we are going to add more changes soon, so please watch closely this repo.
https://github.com/tornadocash/relayer/commit/7d12e182834fca47ad9b05945cfffbeb60d4f457

**Comment by MasterGuardian** [comment]
@rstormsf I think I found the issue - haven't found anywhere that you have to have at least 0.15 (I only had 0.12 or so) ETH in the relayer ethereum address to be recognized by the website.

I am on the latest commit version now.

**Comment by poma** [comment]
Probably we should remove this check for custom relayers
