### ISSUE TITLE
New relayer

### ISSUE THREAD

**Issue by mewwts** [tornadocash/relayer#8]
Hey team,

I'm hosting a relayer at tornado.mewwts.xyz, would love to be added to the list in the app for increased visibility.

**Comment by rstormsf** [comment]
@mewwts 
It doesn't seem like you followed guidelines. 
you are supposed to have 2 domains:
kovan.YOUR_ENS_DOMAIN.eth
mainnet.YOUR_ENS_DOMAIN.eth
https://twitter.com/TornadoCash/status/1202690527927271424

**Comment by mewwts** [comment]
Ah, I didn't see that on github. Hang on, I'll set it up.

**Comment by mewwts** [comment]
Closing this, will come back with a new setup in the new year. Cheers - merry xmas :)
