### ISSUE TITLE
Relayer

### ISSUE THREAD

**Issue by bobbie67** [tornadocash/relayer#9]
I have a relayer which I would like included in the available relayers. Where do I publish the details?

**Comment by bobbie67** [comment]
Are more public relayers needed?

**Comment by poma** [comment]
Each relayer in our current UI was a winner of relayers contest where we had sustained load to verify relayer uptime, and burst loads of hundreds of transactions. This is done to ensure that relayers in UI are high quality with good uptime and fast updates. Currently all our efforts are focused on developing the trusted setup and we don't have time to conduct similar test on each new relayer.

I think in the future we will probably hold another similar relayer contest to test all new relayers that want to be added. Meanwhile, you can promote your relayer in twitter and our tornado telegram group. We already have one such relayer that attracts users with low 0.3% fees
